CREATE TABLE IF NOT EXISTS `hf1_npcs` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `model` varchar(80) NOT NULL,
  `x` double NOT NULL,
  `y` double NOT NULL,
  `z` double NOT NULL,
  `heading` float NOT NULL DEFAULT 0,
  `scenario` varchar(100) DEFAULT NULL,
  `anim_dict` varchar(150) DEFAULT NULL,
  `anim_name` varchar(150) DEFAULT NULL,
  `anim_flag` int NOT NULL DEFAULT 1,
  `invincible` tinyint(1) NOT NULL DEFAULT 1,
  `frozen` tinyint(1) NOT NULL DEFAULT 1,
  `block_events` tinyint(1) NOT NULL DEFAULT 1,
  `can_ragdoll` tinyint(1) NOT NULL DEFAULT 0,
  `collision` tinyint(1) NOT NULL DEFAULT 1,
  `spawn_distance` float NOT NULL DEFAULT 150,
  `metadata` longtext DEFAULT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_hf1_npcs_name` (`name`),
  KEY `idx_hf1_npcs_model` (`model`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
