ScenarioPresets = {
    { label = 'None', value = '' },
    { label = 'Guard Stand', value = 'WORLD_HUMAN_GUARD_STAND' },
    { label = 'Stand Impatient', value = 'WORLD_HUMAN_STAND_IMPATIENT' },
    { label = 'Clipboard', value = 'WORLD_HUMAN_CLIPBOARD' },
    { label = 'Cop Idle', value = 'WORLD_HUMAN_COP_IDLES' },
    { label = 'Drinking', value = 'WORLD_HUMAN_DRINKING' },
    { label = 'Coffee', value = 'WORLD_HUMAN_AA_COFFEE' },
    { label = 'Smoking', value = 'WORLD_HUMAN_SMOKING' },
    { label = 'Lean', value = 'WORLD_HUMAN_LEANING' },
    { label = 'Tourist Map', value = 'WORLD_HUMAN_TOURIST_MAP' },
    { label = 'Mobile Phone', value = 'WORLD_HUMAN_STAND_MOBILE' },
    { label = 'Binoculars', value = 'WORLD_HUMAN_BINOCULARS' },
    { label = 'Paparazzi', value = 'WORLD_HUMAN_PAPARAZZI' },
    { label = 'Muscle Flex', value = 'WORLD_HUMAN_MUSCLE_FLEX' },
    { label = 'Push Ups', value = 'WORLD_HUMAN_PUSH_UPS' },
    { label = 'Sit Ups', value = 'WORLD_HUMAN_SIT_UPS' },
    { label = 'Yoga', value = 'WORLD_HUMAN_YOGA' },
    { label = 'Hammering', value = 'WORLD_HUMAN_HAMMERING' },
    { label = 'Welding', value = 'WORLD_HUMAN_WELDING' },
    { label = 'Janitor', value = 'WORLD_HUMAN_JANITOR' },
    { label = 'Gardener', value = 'WORLD_HUMAN_GARDENER_PLANT' },
}

AnimationPresets = {
    { label = 'None', dict = '', name = '', flag = 1 },
    { label = 'Arms Crossed', dict = 'amb@world_human_hang_out_street@female_arms_crossed@base', name = 'base', flag = 1 },
    { label = 'Hands On Hips', dict = 'amb@world_human_cop_idles@female@base', name = 'base', flag = 1 },
    { label = 'Clipboard', dict = 'missheistdockssetup1clipboard@base', name = 'base', flag = 49 },
    { label = 'Phone', dict = 'cellphone@', name = 'cellphone_text_read_base', flag = 49 },
    { label = 'Think', dict = 'misscarsteal4@aliens', name = 'rehearsal_base_idle_director', flag = 1 },
    { label = 'Fold Arms', dict = 'anim@heists@heist_corona@single_team', name = 'single_team_loop_boss', flag = 1 },
    { label = 'Guard Idle', dict = 'amb@world_human_guard_patrol@male@base', name = 'base', flag = 1 },
}
