PedCatalog = {
    { label = 'Police Officer (Male)', model = 's_m_y_cop_01' },
    { label = 'Police Officer (Female)', model = 's_f_y_cop_01' },
    { label = 'Sheriff (Male)', model = 's_m_y_sheriff_01' },
    { label = 'Sheriff (Female)', model = 's_f_y_sheriff_01' },
    { label = 'Highway Cop', model = 's_m_y_hwaycop_01' },
    { label = 'Security Guard', model = 's_m_m_security_01' },
    { label = 'Prison Guard', model = 's_m_m_prisguard_01' },
    { label = 'Paramedic', model = 's_m_m_paramedic_01' },
    { label = 'Doctor', model = 's_m_m_doctor_01' },
    { label = 'Firefighter', model = 's_m_y_fireman_01' },
    { label = 'Mechanic 1', model = 's_m_y_xmech_01' },
    { label = 'Mechanic 2', model = 's_m_y_xmech_02' },
    { label = 'Car Dealer', model = 's_m_m_autoshop_01' },
    { label = 'Businessman', model = 's_m_m_business_01' },
    { label = 'Businessman 2', model = 's_m_m_highsec_01' },
    { label = 'Businesswoman', model = 'a_f_y_business_01' },
    { label = 'Shop Keeper', model = 'mp_m_shopkeep_01' },
    { label = 'Bartender', model = 's_f_y_bartender_01' },
    { label = 'Waiter', model = 's_m_y_waiter_01' },
    { label = 'Chef', model = 's_m_y_chef_01' },
    { label = 'Construction Worker', model = 's_m_y_construct_01' },
    { label = 'Dock Worker', model = 's_m_m_dockwork_01' },
    { label = 'Garbage Worker', model = 's_m_y_garbage' },
    { label = 'Postal Worker', model = 's_m_m_postal_01' },
    { label = 'Pilot', model = 's_m_m_pilot_01' },
    { label = 'Air Worker', model = 's_m_y_airworker' },
    { label = 'Bus Driver', model = 's_m_o_busker_01' },
    { label = 'Taxi Driver', model = 'a_m_y_stlat_01' },
    { label = 'Valet', model = 's_m_y_valet_01' },
    { label = 'Bouncer', model = 's_m_m_bouncer_01' },
    { label = 'Club Security', model = 's_m_m_highsec_02' },
    { label = 'Banker', model = 'u_m_m_bankman' },
    { label = 'Jeweller', model = 'u_m_m_jewelsec_01' },
    { label = 'Ammu-Nation Clerk', model = 's_m_y_ammucity_01' },
    { label = 'Army Soldier', model = 's_m_y_marine_01' },
    { label = 'Army Soldier 2', model = 's_m_y_marine_03' },
    { label = 'Black Ops', model = 's_m_y_blackops_01' },
    { label = 'Black Ops 2', model = 's_m_y_blackops_02' },
    { label = 'Black Ops 3', model = 's_m_y_blackops_03' },
    { label = 'Gangster 1', model = 'g_m_y_ballaeast_01' },
    { label = 'Gangster 2', model = 'g_m_y_famca_01' },
    { label = 'Gangster 3', model = 'g_m_y_mexgoon_01' },
    { label = 'Lost MC', model = 'g_m_y_lost_01' },
    { label = 'Biker', model = 'u_m_y_bikerchic' },
    { label = 'Beach Male', model = 'a_m_y_beach_01' },
    { label = 'Beach Female', model = 'a_f_y_beach_01' },
    { label = 'Tourist Male', model = 'a_m_m_tourist_01' },
    { label = 'Tourist Female', model = 'a_f_y_tourist_01' },
    { label = 'Hipster Male', model = 'a_m_y_hipster_01' },
    { label = 'Hipster Female', model = 'a_f_y_hipster_01' },
    { label = 'Runner Male', model = 'a_m_y_runner_01' },
    { label = 'Runner Female', model = 'a_f_y_runner_01' },
    { label = 'Bodybuilder', model = 'a_m_y_musclbeac_01' },
    { label = 'Old Man', model = 'a_m_o_genstreet_01' },
    { label = 'Old Woman', model = 'a_f_o_genstreet_01' },
    { label = 'Homeless Male', model = 'a_m_o_tramp_01' },
    { label = 'Homeless Female', model = 'a_f_m_tramp_01' },
    { label = 'Reporter', model = 'u_m_y_rsranger_01' },
    { label = 'Movie Star', model = 'u_m_m_filmdirector' },
    { label = 'Clown', model = 's_m_y_clown_01' },
    { label = 'Mime', model = 's_m_y_mime' },
    { label = 'Jesus', model = 'u_m_m_jesus_01' },
    { label = 'Zombie', model = 'u_m_y_zombie_01' },
}
