CREATE TABLE IF NOT EXISTS `hf1_prop_placer` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL,
    `model` VARCHAR(120) NOT NULL,
    `x` DOUBLE NOT NULL,
    `y` DOUBLE NOT NULL,
    `z` DOUBLE NOT NULL,
    `rot_x` FLOAT NOT NULL DEFAULT 0,
    `rot_y` FLOAT NOT NULL DEFAULT 0,
    `rot_z` FLOAT NOT NULL DEFAULT 0,
    `frozen` TINYINT(1) NOT NULL DEFAULT 1,
    `collision` TINYINT(1) NOT NULL DEFAULT 1,
    `created_by` VARCHAR(100) NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_hf1_prop_placer_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
